### ISSUE TITLE
Make warps great again!

### ISSUE THREAD

**Issue by Brsssh** [ThroneCraft/public#114]
**Describe the bug**

There seems to be some server lag resulting in teleporting not consistently working. Typically the first few times I use /warp /tp or /back they'll work, but after a while it will send the message 'Teleporting to x' or 'warping to x' or 'returning to previous location' but not actually teleport me. If I try to send any command or message after it will give me an error 'Cannot send chat message'. Relogging will make them work again but only for a short time before they stop again.

**Screenshots**

![image](https://user-images.githubusercontent.com/72952343/102166512-3e695000-3e5a-11eb-93e8-b47fb20d8dee.png)

***Minecraft username:***

Brsssh

**Comment by jvdoorn** [comment]
Does this always happen or mainly when warping to other worlds?

**Comment by jvdoorn** [comment]
@Brsssh?

**Comment by Brsssh** [comment]
![image](https://user-images.githubusercontent.com/72952343/103395429-218c7800-4afc-11eb-82af-0ead1d4ea587.png)
I stress tested going between worlds and was unable to duplicate it... I used warps about 20 times, then /back about 20 times. I'm not sure why it happened so frequently to me before but not now unless you've done something to fix it?

**Comment by Brsssh** [comment]
Bew has experienced this now, I've asked him to say what happened to him and maybe we can figure it out

**Comment by Bewby** [comment]
While in Spectator mode, I tried to teleport to someone that was in the build world, while I was in the rp world. It did not teleport me and then I couldn't speak or type any commands in chat. Was given the message 'Cannot send chat message'. Relog made the issue go away. Tried to repeat the same actions and got the bug again, then relogged again. I tried teleporting while in creative mode instead and it worked fine. After it worked once, I couldn't recreate the bug again. Seems to be fairly random.

The bug was removed with a simple relog and really wasn't an inconvenience at all. I don't know if others had been affected worse by it, but from my experience, doesn't seem worth wasting time on if it's hard to find the fix.
