### ISSUE TITLE
Grow custom trees

### ISSUE THREAD

**Issue by Benlier** [ThroneCraft/public#122]
**Is your feature request related to a problem? Please describe.**
The vanilla minceraft trees are ugly and a sore sight amongst the beautiful custom trees of Valoria

**Describe the solution you'd like**
This plugin allows you to replace vanilla trees with schematics https://www.spigotmc.org/resources/owngarden.31709/

**Describe alternatives you've considered**
Lmao make a ticket and get a builder or staff to replace the tree I just grew with a custom one

**Additional context**
I'll add it myself

***Minecraft username:***
BenCoder

**Comment by Brsssh** [comment]
I’m not sure this is really necessary. The only vanilla trees that are supposed to be in the world are at tree farms, where custom trees would be a pain in the ass to cut down. If there are vanilla trees outside of the tree farms that’s what we call grief, and is in fact frowned upon

**Comment by Benlier** [comment]
Perhaps we wouldn't even need those small tree farms anymore, and make woodcutting a bit more realistic

**Comment by Brsssh** [comment]
Idk if Id call having to climb up into a massive flying tree realistic... only way to make it realistic would me to get some plugin that makes the trees fall to the ground when you cut the trunk

**Comment by Benlier** [comment]
Currently you already have to climb up a hovering canopy of leaves to get rid of those. I don't see much of a difference

**Comment by Bewby** [comment]
I 100% support the idea of new custom growing trees, especially considering players do grow default trees and even tho they shouldnt it happens anyways. So it would be nice to just give them a good tree to grow, nothing big though of course.

In regards to making tree cutting more realistic, we can have a giant tree cutting farm that looks like a normal forest but is just a larger fenced area rather than the mess of a tiny space. Wouldnt be possible with ugly default trees but a custom grown one would work perfectly. 100% needs to stay on a farm though
