### ISSUE TITLE
Building Bug

### ISSUE THREAD

**Issue by Zannythica** [ThroneCraft/public#125]
The Bug: When using the same world edit commands as another builder myself and Jollop have received different results. Instead of a flush finish we received air pockets. 

The Commands:
//br sphere gravel,dirt,sand 
/mask sand

What I expected To Happen: I expected that when myself and Jollop used the same command as Brsssh we would receive the same results instead when attempting to make our paths we ended up with a result that was messy and filled with air pockets where gravel would drop. 

**Screenshots**

[https://gyazo.com/4f6356cb609d9d0b6b0ce006f62f3525](url)

***Minecraft username:***

zanithica

**Comment by Brsssh** [comment]
After some testing, I discovered that the bug seems to be in the /brush and //br commands, but not the //brush command, despite the fact that all 3 should be synonymous. That's the reason it was inconsistent. I used //brush, Zani used //br, and Jollop used /brush. This still should be looked into, but a temporary solution is to only use //brush

**Comment by Brsssh** [comment]
Never mind. Jollop tried using all 3 commands and all three had the bugged effect. I have no idea what's happening. It seems to be randomly fluctuating. Sometimes it works, sometimes it doesn't. I had it work for all three commands consecutively, then without even changing the commands, just going back to the items I used as brushes, it messed up again.

**Comment by jvdoorn** [comment]
I've been unable to reproduce this issue. It is possible that it was patched during an update. Could you please try again?
